create table if not exists public.events (
  id bigint generated by default as identity primary key,
  vlr_event_id bigint not null unique,
  title text not null,
  status text not null,
  region text,
  dates text,
  prize text,
  thumb text,
  event_url text,
  raw_payload jsonb not null default '{}'::jsonb,
  last_synced_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists events_status_idx on public.events (status);
create index if not exists events_last_synced_at_idx on public.events (last_synced_at desc);

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  vlr_match_id bigint not null unique,
  event_id bigint not null references public.events(id) on delete cascade,
  slug text,
  event_title text,
  event_series text,
  team_1_name text,
  team_2_name text,
  team_1_score text,
  team_2_score text,
  team_1_is_winner boolean,
  team_2_is_winner boolean,
  scheduled_at timestamptz,
  date_label text,
  match_url text not null,
  vods jsonb not null default '[]'::jsonb,
  status text not null,
  raw_payload jsonb not null default '{}'::jsonb,
  last_synced_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists matches_event_id_idx on public.matches (event_id);
create index if not exists matches_status_idx on public.matches (status);
create index if not exists matches_scheduled_at_idx on public.matches (scheduled_at desc);
create index if not exists matches_last_synced_at_idx on public.matches (last_synced_at desc);

create table if not exists public.event_player_stats (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  player_name text,
  team_name text,
  agents text[] not null default '{}'::text[],
  rounds_played integer,
  rating numeric,
  average_combat_score numeric,
  kill_deaths numeric,
  kill_assists_survived_traded numeric,
  average_damage_per_round numeric,
  kills_per_round numeric,
  assists_per_round numeric,
  first_kills_per_round numeric,
  first_deaths_per_round numeric,
  headshot_percentage numeric,
  clutch_success_percentage numeric,
  raw_payload jsonb not null default '{}'::jsonb,
  last_synced_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  constraint event_player_stats_event_player_team_unique unique (event_id, player_name, team_name)
);

create index if not exists event_player_stats_event_id_idx on public.event_player_stats (event_id);
create index if not exists event_player_stats_rating_idx on public.event_player_stats (rating desc);
create index if not exists event_player_stats_last_synced_at_idx on public.event_player_stats (last_synced_at desc);

create table if not exists public.match_details (
  id bigint generated by default as identity primary key,
  match_id bigint not null unique references public.matches(id) on delete cascade,
  status text,
  source_version text,
  payload jsonb not null default '{}'::jsonb,
  last_synced_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists match_details_last_synced_at_idx on public.match_details (last_synced_at desc);
